import xml.etree.ElementTree as ET
from datetime import date
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any
from uuid import uuid4

from fastapi import APIRouter, File, HTTPException, UploadFile, status
from pydantic import BaseModel

from app.db.h2 import H2ConnectionError, execute_query, execute_update

router = APIRouter(prefix="/invoices", tags=["invoices"])

UPLOAD_DIR = Path("./uploads")
EXTENSION_BY_CONTENT_TYPE = {
    "application/xml": "xml",
    "text/xml": "xml",
}
MAX_FILE_SIZE = 10 * 1024 * 1024

REQUIRED_TAGS = (
    "Issuer",
    "Serie",
    "Numero",
    "Monto",
    "Moneda",
    "FechaEmision",
    "FechaVencimiento",
)


def _init_invoices_table() -> None:
    execute_update(
        """
        CREATE TABLE IF NOT EXISTS invoices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id BIGINT NOT NULL,
            ruc_emisor VARCHAR(11) NOT NULL,
            serie VARCHAR(10) NOT NULL,
            numero VARCHAR(20) NOT NULL,
            monto DECIMAL(12, 2) NOT NULL,
            moneda VARCHAR(3) NOT NULL DEFAULT 'PEN',
            fecha_emision DATE NOT NULL,
            fecha_vencimiento DATE NOT NULL,
            file_path VARCHAR(500) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'uploaded',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


class InvoiceResponse(BaseModel):
    id: int
    company_id: int
    ruc_emisor: str
    serie: str
    numero: str
    monto: Decimal
    moneda: str
    fecha_emision: str
    fecha_vencimiento: str
    file_path: str
    status: str
    created_at: str | None = None


def _normalize_invoice(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": row.get("id"),
        "company_id": row.get("company_id"),
        "ruc_emisor": row.get("ruc_emisor"),
        "serie": row.get("serie"),
        "numero": row.get("numero"),
        "monto": row.get("monto"),
        "moneda": row.get("moneda"),
        "fecha_emision": str(row.get("fecha_emision")) if row.get("fecha_emision") else None,
        "fecha_vencimiento": str(row.get("fecha_vencimiento")) if row.get("fecha_vencimiento") else None,
        "file_path": row.get("file_path"),
        "status": row.get("status"),
        "created_at": str(row.get("created_at")) if row.get("created_at") is not None else None,
    }


def _read_xml_payload(file: UploadFile) -> bytes:
    if file.content_type not in EXTENSION_BY_CONTENT_TYPE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Tipo de archivo no permitido: {file.content_type}. Solo XML.",
        )

    buffer = bytearray()
    while chunk := file.file.read(8192):
        buffer.extend(chunk)
        if len(buffer) > MAX_FILE_SIZE:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail="Archivo excede 10 MB.",
            )

    if not buffer:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="El archivo XML está vacío.",
        )

    return bytes(buffer)


def _parse_invoice_xml(content: bytes) -> dict[str, Any]:
    try:
        root = ET.fromstring(content)
    except ET.ParseError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"XML inválido: {exc}",
        ) from exc

    extracted: dict[str, str] = {}
    missing: list[str] = []
    for tag in REQUIRED_TAGS:
        element = root.find(tag)
        if element is None or element.text is None or not element.text.strip():
            missing.append(tag)
        else:
            extracted[tag] = element.text.strip()

    if missing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"El XML no contiene los campos requeridos: {', '.join(missing)}.",
        )

    ruc_emisor = extracted["Issuer"]
    if len(ruc_emisor) != 11 or not ruc_emisor.isdigit():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Issuer (RUC) debe tener exactamente 11 dígitos.",
        )

    try:
        monto = Decimal(extracted["Monto"])
    except InvalidOperation as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Monto inválido en el XML.",
        ) from exc
    if monto <= 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Monto debe ser mayor a 0.",
        )

    moneda = extracted["Moneda"].upper()
    if len(moneda) != 3:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Moneda debe ser un código de 3 letras (ej. PEN, USD).",
        )

    try:
        fecha_emision = date.fromisoformat(extracted["FechaEmision"])
        fecha_vencimiento = date.fromisoformat(extracted["FechaVencimiento"])
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Fechas deben tener formato YYYY-MM-DD.",
        ) from exc

    if fecha_vencimiento < fecha_emision:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="FechaVencimiento no puede ser anterior a FechaEmision.",
        )

    return {
        "ruc_emisor": ruc_emisor,
        "serie": extracted["Serie"],
        "numero": extracted["Numero"],
        "monto": monto,
        "moneda": moneda,
        "fecha_emision": fecha_emision,
        "fecha_vencimiento": fecha_vencimiento,
    }


def _write_xml_to_disk(content: bytes, company_id: int) -> str:
    company_dir = UPLOAD_DIR / str(company_id)
    company_dir.mkdir(parents=True, exist_ok=True)

    dest = company_dir / f"{uuid4().hex}.xml"
    dest.write_bytes(content)

    return str(dest)


@router.get("", response_model=list[InvoiceResponse])
def list_invoices():
    try:
        _init_invoices_table()

        rows = execute_query(
            """
            SELECT id, company_id, ruc_emisor, serie, numero, monto, moneda,
                   fecha_emision, fecha_vencimiento, file_path, status, created_at
            FROM invoices
            ORDER BY id DESC
            """
        )

        return [_normalize_invoice(row) for row in rows]
    except H2ConnectionError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@router.post("", response_model=InvoiceResponse, status_code=status.HTTP_201_CREATED)
def upload_invoice(file: UploadFile = File(...)):
    company_id = 1  # TODO: sacar de get_current_user cuando auth esté listo

    content = _read_xml_payload(file)
    parsed = _parse_invoice_xml(content)
    file_path = _write_xml_to_disk(content, company_id)

    try:
        _init_invoices_table()

        execute_update(
            """
            INSERT INTO invoices (
                company_id, ruc_emisor, serie, numero, monto, moneda,
                fecha_emision, fecha_vencimiento, file_path
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                company_id,
                parsed["ruc_emisor"],
                parsed["serie"],
                parsed["numero"],
                str(parsed["monto"]),
                parsed["moneda"],
                parsed["fecha_emision"].isoformat(),
                parsed["fecha_vencimiento"].isoformat(),
                file_path,
            ],
        )

        rows = execute_query(
            """
            SELECT id, company_id, ruc_emisor, serie, numero, monto, moneda,
                   fecha_emision, fecha_vencimiento, file_path, status, created_at
            FROM invoices
            WHERE file_path = ?
            """,
            [file_path],
        )

        return _normalize_invoice(rows[0])

    except H2ConnectionError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    except HTTPException:
        raise

    except Exception as exc:
        raise HTTPException(
            status_code=400,
            detail="No se pudo registrar la factura. Verifica el contenido del XML.",
        ) from exc
