from pathlib import Path
from typing import Any

import jaydebeapi

from app.core.config import settings


class H2ConnectionError(RuntimeError):
    pass


def _get_h2_jar_path() -> str:
    jar_path = Path(settings.h2_jar_path)

    if not jar_path.is_absolute():
        jar_path = Path.cwd() / jar_path

    if not jar_path.exists():
        raise H2ConnectionError(
            f"No se encontró el driver H2 en: {jar_path}. "
            "Ejecuta: python scripts/download_h2.py"
        )

    return str(jar_path.resolve())


def get_connection():
    """
    Crea una conexión nueva hacia H2 usando JDBC.
    Se abre y se cierra una conexión por operación para mantenerlo simple.
    """
    try:
        return jaydebeapi.connect(
            settings.h2_driver,
            settings.h2_jdbc_url,
            [settings.h2_user, settings.h2_password],
            _get_h2_jar_path(),
        )
    except Exception as exc:
        raise H2ConnectionError(
            "No se pudo conectar a H2. Verifica que el servidor H2 esté levantado "
            "con: python scripts/run_h2_server.py"
        ) from exc


def execute_query(
    sql: str,
    params: list[Any] | tuple[Any, ...] | None = None,
) -> list[dict[str, Any]]:
    conn = get_connection()
    cursor = None

    try:
        cursor = conn.cursor()
        cursor.execute(sql, params or [])

        columns = [column[0].lower() for column in cursor.description]
        rows = cursor.fetchall()

        return [dict(zip(columns, row)) for row in rows]
    finally:
        if cursor is not None:
            cursor.close()

        conn.close()


def execute_update(
    sql: str,
    params: list[Any] | tuple[Any, ...] | None = None,
) -> int:
    conn = get_connection()
    cursor = None

    try:
        cursor = conn.cursor()
        cursor.execute(sql, params or [])
        conn.commit()

        return cursor.rowcount
    finally:
        if cursor is not None:
            cursor.close()

        conn.close()


def ping_database() -> dict[str, Any]:
    rows = execute_query("SELECT 1 AS ok")

    return {
        "connected": True,
        "result": rows[0]["ok"],
    }


def init_database() -> None:
    execute_update(
        """
        CREATE TABLE IF NOT EXISTS clients (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_number VARCHAR(20) NOT NULL UNIQUE,
            business_name VARCHAR(150) NOT NULL,
            email VARCHAR(120) NOT NULL UNIQUE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def seed_database() -> None:
    init_database()

    rows = execute_query("SELECT COUNT(*) AS total FROM clients")
    total = rows[0]["total"]

    if total == 0:
        execute_update(
            """
            INSERT INTO clients (document_number, business_name, email)
            VALUES (?, ?, ?)
            """,
            ["20600000001", "Empresa Demo SAC", "demo@factoring.test"],
        )